---
abstract: 'Get subroutine arguments %args from hash (%args) :)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-GetArgs-Hash
requires:
  Sub::Spec: 0.14
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-GetArgs-Hash/
  repository: http://github.com/sharyanto/perl-Sub-Spec-GetArgs-Hash
version: 0.02
